"""Append paired training traces while preserving an audited pilot's validation."""
from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor
from copy import deepcopy
import json
from pathlib import Path
import subprocess
import sys
import time

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from scripts.collect_prefusion_acceptance import (
    collect_prompt, materialize, require_empty_destination, select_prompts, sha256,
    validate_reference_split,
)
from scripts.audit_prefusion_cache import audit, source_path
from scripts.train_prefusion_acceptance import validate_audit, validate_cache
from scripts.train_context_attention import atomic_json, buffered_backup


def new_training_prompts(selected, previous):
    seen = {int(row["prompt_id"]) for row in previous}
    result = []
    for group, row in selected:
        pid = int(row["manifest_index"])
        if group != "train" or pid in seen:
            continue
        seen.add(pid)
        result.append(row)
    return result


def cycle_limit(current, target, maximum):
    if current >= target or maximum < 1:
        raise ValueError("No remaining collection budget")
    return min(maximum, target-current)


def assert_preserved(base, grown):
    for path in (base / "val").glob("*.npy"):
        if sha256(path) != sha256(grown / "val" / path.name):
            raise ValueError(f"Validation changed: {path.name}")
    for path in (base / "train").glob("*.npy"):
        before = np.load(path, mmap_mode="r", allow_pickle=False)
        after = np.load(grown / "train" / path.name, mmap_mode="r", allow_pickle=False)
        if len(after) < len(before) or not np.array_equal(before, after[:len(before)]):
            raise ValueError(f"Existing training prefix changed: {path.name}")


def main():
    p = argparse.ArgumentParser(description=__doc__)
    for name in ("base-cache", "output-dir", "persistent-dir"):
        p.add_argument("--" + name, type=Path, required=True)
    p.add_argument("--target-train-rows", type=int, default=100000)
    p.add_argument("--candidate-prompts", type=int, default=6000)
    cli = p.parse_args()
    base, output, persistent = cli.base_cache, cli.output_dir, cli.persistent_dir
    for path in (output, persistent):
        require_empty_destination(path)
        if path.resolve() == base.resolve():
            raise ValueError("Cannot overwrite base cache")
    if output.resolve() == persistent.resolve():
        raise ValueError("Temporary and persistent storage must differ")
    torch.set_num_threads(4)
    validate_audit(base)
    validate_cache(base)
    parent = json.loads((base / "manifest.json").read_text())
    if cli.target_train_rows <= parent["train_rows"]:
        raise ValueError("Target must exceed existing training rows")
    config = deepcopy(parent["collection_config"])
    repository = Path(__file__).resolve().parents[1]
    # Refuse to mix trajectories generated by different models or collector code.
    for category in ("hashes", "source_sha256", "model_files_sha256"):
        for original, expected in config[category].items():
            live = repository / original if category == "source_sha256" else Path(original)
            if not live.is_file() or sha256(live) != expected:
                raise ValueError(f"Parent collection input changed: {original}")
    reference = json.loads(Path(config["reference_cache_manifest"]).read_text())
    split_dir = Path(config["split_dir"])
    validate_reference_split(split_dir, reference)
    selected = select_prompts(Path(config["manifest"]), split_dir, reference,
                              cli.candidate_prompts, config["val_prompts"], config["seed"])
    candidates = new_training_prompts(selected, config["selected_prompts"])
    if len(candidates) * config["max_cycles"] < cli.target_train_rows-parent["train_rows"]:
        raise ValueError("Candidate pool cannot reach requested row count")
    output.mkdir(parents=True, exist_ok=False)
    (output / "shards").mkdir()
    (output / "val").mkdir()
    records = deepcopy(parent["shards"])
    copied = []
    for record in records:
        if "path" in record:
            source = base / "shards" / Path(record["path"]).name
            destination = output / "shards" / source.name
            buffered_backup(source, destination)
            record["path"] = str(destination)
            copied.append(destination)
        receipt = output / "shards" / f"{record['prompt_id']}.json"
        atomic_json(receipt, record)
        copied.append(receipt)
    for source in [base / "fusion.pt", *sorted((base / "val").glob("*.npy"))]:
        destination = output / source.relative_to(base)
        buffered_backup(source, destination)
        copied.append(destination)
    for original, relative in config.get("provenance_files", {}).items():
        buffered_backup(source_path(base, original, config["provenance_files"]), output / relative)
        copied.append(output / relative)
    for name in ("manifest.json", "audit.json"):
        destination = output / "provenance" / ("parent_" + name)
        buffered_backup(base / name, destination)
        config["hashes"][str(base / name)] = sha256(destination)
        config["provenance_files"][str(base / name)] = str(destination.relative_to(output))
        copied.append(destination)
    config["source_sha256"]["scripts/grow_prefusion_acceptance.py"] = sha256(Path(__file__))
    config.update({"output_dir": str(output), "persistent_dir": str(persistent),
        "target_train_rows": cli.target_train_rows,
        "git_commit": subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip(),
        "parent_train_rows": parent["train_rows"], "candidate_prompts": cli.candidate_prompts,
        "fixed_val_sha256": {path.name: sha256(path) for path in (base / "val").glob("*.npy")}})
    # Immutable plan and per-prompt receipts keep interrupted collections recoverable.
    atomic_json(output / "expansion_plan.json", {"config": config, "candidates": [
        {"prompt_id": int(r["manifest_index"]), "content_sha256": r["content_sha256"]} for r in candidates]})
    copied.append(output / "expansion_plan.json")
    args = argparse.Namespace(**config)
    torch.manual_seed(args.seed)
    torch.backends.cuda.matmul.allow_tf32 = False
    from transformers import AutoTokenizer, AutoModelForCausalLM
    import transformers
    from dflash.model import DFlashDraftModel
    if torch.__version__ != config["torch"] or transformers.__version__ != config["transformers"]:
        raise ValueError("Runtime differs from parent collection")
    tokenizer = AutoTokenizer.from_pretrained(args.model, local_files_only=True)
    target = AutoModelForCausalLM.from_pretrained(args.model, torch_dtype=torch.bfloat16,
        attn_implementation="sdpa", local_files_only=True).cuda().eval().requires_grad_(False)
    draft = DFlashDraftModel.from_pretrained(args.draft_model, torch_dtype=torch.bfloat16,
        attn_implementation="sdpa", local_files_only=True).cuda().eval().requires_grad_(False)
    started, rows = time.monotonic(), parent["train_rows"]
    with ThreadPoolExecutor(max_workers=1) as pool:
        def backup(paths):
            for path in paths:
                buffered_backup(path, persistent / path.relative_to(output))
        futures = [pool.submit(backup, copied)]
        for i, row in enumerate(candidates):
            args.max_cycles = cycle_limit(rows, cli.target_train_rows, config["max_cycles"])
            data, info = collect_prompt(row, target, draft, tokenizer, args)
            pid = int(row["manifest_index"])
            record = {"group": "train", "prompt_id": pid, "collection_max_cycles": args.max_cycles, **info}
            paths = []
            if data is not None:
                path = output / "shards" / f"{pid}.npz"
                np.savez(path, **data)
                record.update({"path": str(path), "sha256": sha256(path)})
                rows += info["rows"]
                paths.append(path)
            records.append(record)
            config["selected_prompts"].append({"prompt_id": pid, "group": "train",
                                               "content_sha256": row["content_sha256"]})
            receipt = output / "shards" / f"{pid}.json"
            atomic_json(receipt, record)
            futures.append(pool.submit(backup, paths + [receipt]))
            # Bound the backup queue; surface PVC errors during collection.
            pending = []
            for future in futures:
                if future.done():
                    future.result()
                else:
                    pending.append(future)
            futures = pending
            if len(futures) >= 64:
                futures.pop(0).result()
            progress = {"train_rows": rows, "target_train_rows": cli.target_train_rows,
                "new_prompts_processed": i+1, "elapsed_s": time.monotonic()-started,
                "new_rows": rows-parent["train_rows"], "latest": record}
            atomic_json(output / "progress.json", progress)
            print(json.dumps(progress), flush=True)
            if rows == cli.target_train_rows:
                break
        if rows != cli.target_train_rows:
            raise RuntimeError(f"Candidates exhausted at {rows}; receipts preserved")
        del target, draft
        torch.cuda.empty_cache()
        materialize([r for r in records if r["group"] == "train" and "path" in r],
                    output / "train", parent["input_dim"], parent["fused_dim"])
        assert_preserved(base, output)
        manifest = {**parent, "train_rows": rows, "collection_config": config,
                    "shards": records, "elapsed_s": time.monotonic()-started}
        atomic_json(output / "manifest.json", manifest)
        atomic_json(output / "config.json", config)
        audit(output, "cuda")
        futures.append(pool.submit(backup, list((output / "train").glob("*.npy")) + [
            output / name for name in ("manifest.json", "config.json", "audit.json", "progress.json")]))
        for future in futures:
            future.result()
    print(json.dumps({"complete": True, "train_rows": rows, "val_rows": parent["val_rows"],
                      "validation_byte_identical": True, "audit_passed": True}), flush=True)


if __name__ == "__main__":
    main()
